"""core commerce schema

Revision ID: 2419898e3bdb
Revises: 
Create Date: 2026-09-08 12:32:05.980635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2419898e3bdb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands'))
    )
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('retailers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retailers'))
    )
    op.create_index(op.f('ix_retailers_slug'), 'retailers', ['slug'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_products_brand_id_brands')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_table('variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('mpn', sa.String(length=120), nullable=True),
    sa.Column('gtin', sa.String(length=14), nullable=True),
    sa.Column('upc', sa.String(length=12), nullable=True),
    sa.Column('ean', sa.String(length=13), nullable=True),
    sa.Column('specs', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_variants_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variants'))
    )
    op.create_index(op.f('ix_variants_ean'), 'variants', ['ean'], unique=False)
    op.create_index(op.f('ix_variants_gtin'), 'variants', ['gtin'], unique=False)
    op.create_index(op.f('ix_variants_mpn'), 'variants', ['mpn'], unique=False)
    op.create_index(op.f('ix_variants_product_id'), 'variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_variants_sku'), 'variants', ['sku'], unique=True)
    op.create_index(op.f('ix_variants_upc'), 'variants', ['upc'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('alt_text', sa.String(length=300), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_images_variant_id_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images'))
    )
    op.create_index(op.f('ix_images_variant_id'), 'images', ['variant_id'], unique=False)
    op.create_table('retailer_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('retailer_id', sa.Integer(), nullable=False),
    sa.Column('retailer_sku', sa.String(length=150), nullable=True),
    sa.Column('product_url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('seller_name', sa.String(length=200), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], name=op.f('fk_retailer_listings_retailer_id_retailers')),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_retailer_listings_variant_id_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retailer_listings'))
    )
    op.create_index(op.f('ix_retailer_listings_retailer_id'), 'retailer_listings', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_retailer_listings_variant_id'), 'retailer_listings', ['variant_id'], unique=False)
    op.create_table('price_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retailer_listing_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('list_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('availability_text', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['retailer_listing_id'], ['retailer_listings.id'], name=op.f('fk_price_records_retailer_listing_id_retailer_listings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_records'))
    )
    op.create_index(op.f('ix_price_records_collected_at'), 'price_records', ['collected_at'], unique=False)
    op.create_index(op.f('ix_price_records_retailer_listing_id'), 'price_records', ['retailer_listing_id'], unique=False)
    op.create_table('review_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retailer_listing_id', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('positive_aspects', sa.JSON(), nullable=True),
    sa.Column('negative_aspects', sa.JSON(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['retailer_listing_id'], ['retailer_listings.id'], name=op.f('fk_review_summaries_retailer_listing_id_retailer_listings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_summaries'))
    )
    op.create_index(op.f('ix_review_summaries_collected_at'), 'review_summaries', ['collected_at'], unique=False)
    op.create_index(op.f('ix_review_summaries_retailer_listing_id'), 'review_summaries', ['retailer_listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_summaries_retailer_listing_id'), table_name='review_summaries')
    op.drop_index(op.f('ix_review_summaries_collected_at'), table_name='review_summaries')
    op.drop_table('review_summaries')
    op.drop_index(op.f('ix_price_records_retailer_listing_id'), table_name='price_records')
    op.drop_index(op.f('ix_price_records_collected_at'), table_name='price_records')
    op.drop_table('price_records')
    op.drop_index(op.f('ix_retailer_listings_variant_id'), table_name='retailer_listings')
    op.drop_index(op.f('ix_retailer_listings_retailer_id'), table_name='retailer_listings')
    op.drop_table('retailer_listings')
    op.drop_index(op.f('ix_images_variant_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_variants_upc'), table_name='variants')
    op.drop_index(op.f('ix_variants_sku'), table_name='variants')
    op.drop_index(op.f('ix_variants_product_id'), table_name='variants')
    op.drop_index(op.f('ix_variants_mpn'), table_name='variants')
    op.drop_index(op.f('ix_variants_gtin'), table_name='variants')
    op.drop_index(op.f('ix_variants_ean'), table_name='variants')
    op.drop_table('variants')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_retailers_slug'), table_name='retailers')
    op.drop_table('retailers')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
