"""add business domain tables

Revision ID: 7bb25b5b2112
Revises: b69ad18b82d9
Create Date: 2026-09-12 12:06:35.094841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb25b5b2112'
down_revision: Union[str, None] = 'b69ad18b82d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('startup_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('target_customer', sa.Text(), nullable=True),
    sa.Column('business_model', sa.Text(), nullable=True),
    sa.Column('experience_level', sa.String(length=40), nullable=True),
    sa.Column('delivery_mode', sa.String(length=20), nullable=True),
    sa.Column('time_commitment', sa.String(length=40), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("stage IN ('idea', 'validation', 'planning', 'pre_launch', 'launched', 'operating')", name=op.f('ck_business_projects_ck_business_projects_stage')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_business_projects_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_projects'))
    )
    op.create_index(op.f('ix_business_projects_user_id'), 'business_projects', ['user_id'], unique=False)
    op.create_table('budget_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_project_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_budget_items_ck_budget_items_amount_non_negative')),
    sa.ForeignKeyConstraint(['business_project_id'], ['business_projects.id'], name=op.f('fk_budget_items_business_project_id_business_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_items'))
    )
    op.create_index(op.f('ix_budget_items_business_project_id'), 'budget_items', ['business_project_id'], unique=False)
    op.create_table('business_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high')", name=op.f('ck_business_tasks_ck_business_tasks_priority')),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed')", name=op.f('ck_business_tasks_ck_business_tasks_status')),
    sa.ForeignKeyConstraint(['business_project_id'], ['business_projects.id'], name=op.f('fk_business_tasks_business_project_id_business_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_tasks'))
    )
    op.create_index(op.f('ix_business_tasks_business_project_id'), 'business_tasks', ['business_project_id'], unique=False)
    op.create_index('ix_business_tasks_project_week', 'business_tasks', ['business_project_id', 'week'], unique=False)
    op.create_table('financial_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_project_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type IN ('revenue', 'expense')", name=op.f('ck_financial_entries_ck_financial_entries_type')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_financial_entries_ck_financial_entries_amount_non_negative')),
    sa.ForeignKeyConstraint(['business_project_id'], ['business_projects.id'], name=op.f('fk_financial_entries_business_project_id_business_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_entries'))
    )
    op.create_index(op.f('ix_financial_entries_business_project_id'), 'financial_entries', ['business_project_id'], unique=False)
    op.create_index('ix_financial_entries_project_date', 'financial_entries', ['business_project_id', 'entry_date'], unique=False)
    op.create_table('idea_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_project_id', sa.Integer(), nullable=False),
    sa.Column('score_demand', sa.Integer(), nullable=False),
    sa.Column('score_differentiation', sa.Integer(), nullable=False),
    sa.Column('score_business_model', sa.Integer(), nullable=False),
    sa.Column('score_capital', sa.Integer(), nullable=False),
    sa.Column('score_operational', sa.Integer(), nullable=False),
    sa.Column('score_gtm', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('verdict', sa.String(length=60), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("confidence IN ('Low', 'Medium', 'High')", name=op.f('ck_idea_validations_ck_idea_validations_confidence')),
    sa.ForeignKeyConstraint(['business_project_id'], ['business_projects.id'], name=op.f('fk_idea_validations_business_project_id_business_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idea_validations'))
    )
    op.create_index(op.f('ix_idea_validations_business_project_id'), 'idea_validations', ['business_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idea_validations_business_project_id'), table_name='idea_validations')
    op.drop_table('idea_validations')
    op.drop_index('ix_financial_entries_project_date', table_name='financial_entries')
    op.drop_index(op.f('ix_financial_entries_business_project_id'), table_name='financial_entries')
    op.drop_table('financial_entries')
    op.drop_index('ix_business_tasks_project_week', table_name='business_tasks')
    op.drop_index(op.f('ix_business_tasks_business_project_id'), table_name='business_tasks')
    op.drop_table('business_tasks')
    op.drop_index(op.f('ix_budget_items_business_project_id'), table_name='budget_items')
    op.drop_table('budget_items')
    op.drop_index(op.f('ix_business_projects_user_id'), table_name='business_projects')
    op.drop_table('business_projects')
    # ### end Alembic commands ###
