import type { Metadata } from "next";
import { Container } from "@/components/layout/Container";
import { Card } from "@/components/ui/Card";
import { COMPANY_NAME, SITE_NAME } from "@/lib/siteConfig";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: `The terms governing use of ${SITE_NAME}, operated by ${COMPANY_NAME}.`,
};

export default function TermsPage() {
  return (
    <Container className="py-12">
      <div className="mx-auto flex max-w-2xl flex-col gap-6">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 sm:text-3xl">Terms of Use</h1>
          <p className="mt-2 text-sm text-slate-500">Last updated: {new Date().getFullYear()}</p>
        </div>

        <Card className="flex flex-col gap-4 p-6 text-sm leading-relaxed text-slate-700 sm:p-8">
          <p>
            These Terms of Use (&ldquo;Terms&rdquo;) govern your use of {SITE_NAME}, operated by{" "}
            {COMPANY_NAME} (&ldquo;we,&rdquo; &ldquo;us&rdquo;). By using {SITE_NAME}, you agree to
            these Terms.
          </p>

          <h2 className="mt-2 text-base font-semibold text-slate-900">1. What {SITE_NAME} is</h2>
          <p>
            {SITE_NAME} is business planning and operating software. It helps you validate a business
            idea, plan a launch, budget startup costs, run financial calculations, track a launch
            roadmap, and record revenue and expenses — including through an AI copilot.
          </p>

          <h2 className="mt-2 text-base font-semibold text-slate-900">
            2. Not financial, legal, or tax advice
          </h2>
          <p>
            Nothing on {SITE_NAME} is financial, legal, investment, accounting, or tax advice.
            Validation reports, financial projections, and AI responses are planning estimates based
            on the information you provide and the assumptions stated alongside them — they are not
            a guarantee of profit, success, demand, or return on any business idea. Confirm important
            decisions with a qualified professional.
          </p>

          <h2 className="mt-2 text-base font-semibold text-slate-900">
            3. Your business and financial data
          </h2>
          <p>
            You are responsible for the accuracy of the business, budget, task, and financial
            information you enter. {SITE_NAME} calculates summaries and reports from exactly what you
            enter — it does not verify your figures against any external source, and it does not
            fabricate revenue, expenses, or other financial data on your behalf.
          </p>

          <h2 className="mt-2 text-base font-semibold text-slate-900">
            4. AI-generated content
          </h2>
          <p>
            Ask Start Currency and idea validation are informational aids. Deterministic calculations
            (break-even, margin, pricing) are computed by code; narrative analysis is generated by an
            AI model and may not always be complete or accurate. Use your own judgment, especially
            for decisions with real financial consequences.
          </p>

          <h2 className="mt-2 text-base font-semibold text-slate-900">5. Acceptable use</h2>
          <p>
            You agree not to misuse {SITE_NAME} — including attempting to disrupt the service,
            scraping or automating access outside of any published API, attempting to access another
            user&apos;s business or financial data, circumventing security measures, or using the
            service for unlawful purposes.
          </p>

          <h2 className="mt-2 text-base font-semibold text-slate-900">6. No warranty</h2>
          <p>
            {SITE_NAME} is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis,
            without warranties of any kind, to the extent permitted by law. We do not guarantee
            uninterrupted or error-free operation.
          </p>

          <h2 className="mt-2 text-base font-semibold text-slate-900">
            7. Limitation of liability
          </h2>
          <p>
            To the extent permitted by law, {COMPANY_NAME} is not liable for indirect, incidental, or
            consequential damages arising from your use of {SITE_NAME}, including business decisions
            made using its calculators, validation reports, or AI copilot. Nothing in these Terms
            limits liability that cannot be limited under applicable law.
          </p>

          <h2 className="mt-2 text-base font-semibold text-slate-900">8. Changes to these Terms</h2>
          <p>
            We may update these Terms from time to time. Continued use of {SITE_NAME} after an update
            constitutes acceptance of the revised Terms.
          </p>

          <h2 className="mt-2 text-base font-semibold text-slate-900">9. Contact</h2>
          <p>
            Questions about these Terms can be sent through our{" "}
            <a href="/contact" className="font-medium text-violet-600 hover:text-violet-700">
              Contact page
            </a>
            .
          </p>
        </Card>
      </div>
    </Container>
  );
}
